model:
  type: "classification"
  backbone: "vovnet-19-slim-dw"
training:
  optimizer: 
    type: "SGD"
    lr: 1e-2
    momentum: 0.9
    weight_decay: 1e-5
  lr_scheduler:
    start_lr: 1e-3
    max_lr: 1e-2
    end_lr: 1e-8
    warmup_fraction: 0.1
  epochs: 10
  batch_size: 100
  eval_batch_size: 100
  