model:
  type: "classification"
  backbone: "vovnet-19-slim-dw"
training:
  optimizer: 
    type: "SGD"
    lr: 5e-5
    momentum: 0.9
    weight_decay: 1e-5
  epochs: 30
  gpu: True
  batch_size: 10
  eval_batch_size: 1
  save_best: True
  