model:
  type: "detection"
  backbone: "vovnet"
  fpn: "retinanet"
training:
  optimizer: 
    type: "SGD"
    lr: 5e-5
    momentum: 0.9
    weight_decay: 1e-5
  epochs: 30
  gpu: True
  train_batch_size: 25
  eval_batch_size: 64
  save_best: True
  